global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'consul-services'
    consul_sd_configs:
      - server: 'host.docker.internal:8500'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: [__meta_consul_service_address, __meta_consul_service_port]
        separator: ':'
        target_label: __address__
      - source_labels: [__address__]
        regex: '(localhost|127\.0\.0\.1):(.*)'
        replacement: 'host.docker.internal:${2}'
        target_label: __address__
      - source_labels: [job]
        regex: 'consul'
        action: drop
    metrics_path: /management/prometheus
