# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OWM1YTI0NDg4ZmFmNThkZDg2YmFmYmFhZmRiNjc1YzZlMDdlMzY1MzgwMWEzMWZjYTIyOTY2OTFiYjM3ZDk5ODhjMGFhZmQ5ZjQ0Y2YxYzAyOWZkZmQwOTkwMTBlNDA0YzJmYzY1YjFkZmMyMjlhYjczMzljOWZiNTQ2NGU4NDY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
