configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NmMxM2ZmYWMyZTFlY2QxOGYzMWFmY2NkM2NjNGNjODQ5M2E2MGEwOTdlMzMzYmMzMzUxZTg3ZTJjYTViYTE2OTA5Y2EwNjQ1YzQwMmVhMWQxMTJiYmI4MWZiZWRmMWRhZmQ3ZWNiYjM5ZjM3NTczZjJkNGUzYTAwMzVlZDM5Zjk=
