# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: sunusantegatewayservice
services:
  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=remote-write-receiver'
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
  loki:
    image: grafana/loki:3.0.0
    volumes:
      - ../../../../docker/loki/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100
  tempo:
    image: grafana/tempo:2.5.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ../../../../docker/tempo/tempo-config.yml:/etc/tempo.yaml
    ports:
      - 3200:3200
      - 9411:9411 # zipkin
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana:11.0.0
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
