package dev.sunusante.dmp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MedicalEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalEntryAllPropertiesEquals(MedicalEntry expected, MedicalEntry actual) {
        assertMedicalEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertMedicalEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalEntryAllUpdatablePropertiesEquals(MedicalEntry expected, MedicalEntry actual) {
        assertMedicalEntryUpdatableFieldsEquals(expected, actual);
        assertMedicalEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalEntryAutoGeneratedPropertiesEquals(MedicalEntry expected, MedicalEntry actual) {
        assertThat(expected)
            .as("Verify MedicalEntry auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalEntryUpdatableFieldsEquals(MedicalEntry expected, MedicalEntry actual) {
        assertThat(expected)
            .as("Verify MedicalEntry relevant properties")
            .satisfies(e -> assertThat(e.getPatientPseudo()).as("check patientPseudo").isEqualTo(actual.getPatientPseudo()))
            .satisfies(e -> assertThat(e.getCategory()).as("check category").isEqualTo(actual.getCategory()))
            .satisfies(e -> assertThat(e.getContent()).as("check content").isEqualTo(actual.getContent()))
            .satisfies(
                e -> assertThat(e.getConfidentialityLevel()).as("check confidentialityLevel").isEqualTo(actual.getConfidentialityLevel())
            )
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(actual.getLastModifiedBy()))
            .satisfies(e -> assertThat(e.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(actual.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalEntryUpdatableRelationshipsEquals(MedicalEntry expected, MedicalEntry actual) {}
}
