services:
  consul:
    image: hashicorp/consul:1.19
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: consul agent -dev -ui -client 0.0.0.0 -log-level info
  
  consul-config-loader:
    image: jhipster/consul-config-loader:v0.4.1
    volumes:
      - ./config:/config
    environment:
      - INIT_SLEEP_SECONDS=5
      - CONSUL_URL=consul
      - CONSUL_PORT=8500
