global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'consul-services'
    consul_sd_configs:
      - server: 'host.docker.internal:8500'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: [__meta_consul_service_metadata_prometheus_path]
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_consul_service_metadata_prometheus_port]
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
