package dev.sunusante.patient.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LegalGuardianAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegalGuardianAllPropertiesEquals(LegalGuardian expected, LegalGuardian actual) {
        assertLegalGuardianAutoGeneratedPropertiesEquals(expected, actual);
        assertLegalGuardianAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegalGuardianAllUpdatablePropertiesEquals(LegalGuardian expected, LegalGuardian actual) {
        assertLegalGuardianUpdatableFieldsEquals(expected, actual);
        assertLegalGuardianUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegalGuardianAutoGeneratedPropertiesEquals(LegalGuardian expected, LegalGuardian actual) {
        assertThat(expected)
            .as("Verify LegalGuardian auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegalGuardianUpdatableFieldsEquals(LegalGuardian expected, LegalGuardian actual) {
        assertThat(expected)
            .as("Verify LegalGuardian relevant properties")
            .satisfies(e -> assertThat(e.getGuardianType()).as("check guardianType").isEqualTo(actual.getGuardianType()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(actual.getLastModifiedBy()))
            .satisfies(e -> assertThat(e.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(actual.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegalGuardianUpdatableRelationshipsEquals(LegalGuardian expected, LegalGuardian actual) {
        assertThat(expected)
            .as("Verify LegalGuardian relationships")
            .satisfies(e -> assertThat(e.getDependent()).as("check dependent").isEqualTo(actual.getDependent()));
    }
}
