package dev.sunusante.patient.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PatientConsentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientConsentAllPropertiesEquals(PatientConsent expected, PatientConsent actual) {
        assertPatientConsentAutoGeneratedPropertiesEquals(expected, actual);
        assertPatientConsentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientConsentAllUpdatablePropertiesEquals(PatientConsent expected, PatientConsent actual) {
        assertPatientConsentUpdatableFieldsEquals(expected, actual);
        assertPatientConsentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientConsentAutoGeneratedPropertiesEquals(PatientConsent expected, PatientConsent actual) {
        assertThat(expected)
            .as("Verify PatientConsent auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientConsentUpdatableFieldsEquals(PatientConsent expected, PatientConsent actual) {
        assertThat(expected)
            .as("Verify PatientConsent relevant properties")
            .satisfies(e -> assertThat(e.getPatientPseudo()).as("check patientPseudo").isEqualTo(actual.getPatientPseudo()))
            .satisfies(e -> assertThat(e.getDoctorLogin()).as("check doctorLogin").isEqualTo(actual.getDoctorLogin()))
            .satisfies(e -> assertThat(e.getConsentDate()).as("check consentDate").isEqualTo(actual.getConsentDate()))
            .satisfies(e -> assertThat(e.getExpiryDate()).as("check expiryDate").isEqualTo(actual.getExpiryDate()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientConsentUpdatableRelationshipsEquals(PatientConsent expected, PatientConsent actual) {}
}
